name: client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  otpless_flutter: ^2.1.8
  firebase_messaging: ^15.1.0
  get: ^4.6.6
  card_swiper: ^3.0.1
  provider: ^6.1.2
  animated_custom_dropdown: ^3.1.1
  dio: ^5.7.0
  intl: any
  fluttertoast: ^8.2.8
  http: any
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  permission_handler: ^10.2.0
  infinite_scroll_pagination: ^4.0.0
  flutter_riverpod: ^2.5.1
  path: ^1.9.0
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf